/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_client3d_free: (a: number, b: number) => void;
export const client3d_draw: (a: number) => void;
export const client3d_reset: (a: number) => void;
export const client3d_resize: (a: number, b: number, c: number) => void;
export const client3d_setAutoRotate: (a: number, b: number) => void;
export const createClient3d: (a: any) => any;
export const __wbg_client_free: (a: number, b: number) => void;
export const __wbg_get_size_height: (a: number) => number;
export const __wbg_get_size_width: (a: number) => number;
export const __wbg_set_size_height: (a: number, b: number) => void;
export const __wbg_set_size_width: (a: number, b: number) => void;
export const __wbg_size_free: (a: number, b: number) => void;
export const client_draw: (a: number) => void;
export const client_resize: (a: number, b: number, c: number) => void;
export const createClient: (a: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h165335fa58188c1a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h6340a3d24bc9929e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h117acbe3fd438207: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h9651559ad17dc211: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf103af991beac1e6: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__hed178cedbd723e99: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
