export { useAutoplay } from "./useAutoplay";
export { useDrawing, type DrawingStroke } from "./useDrawing";
export { useKeyboardNavigation } from "./useKeyboardNavigation";
export { useLaserPointer } from "./useLaserPointer";
export { usePresenterSync } from "./usePresenterSync";
export { useRecording } from "./useRecording";
export { useSlideDeck, type SlideDeckComposable } from "./useSlideDeck";
export { useSpotlight } from "./useSpotlight";
export { useTimer } from "./useTimer";
export { useTouchNavigation } from "./useTouchNavigation";
export { useZoom } from "./useZoom";
