import type { Email } from '../../shared/types/email';

export const emails: Email[] = [
  { id: 1, from: 'X', subject: 'New login to X from ChromeDesktop on Windows', body: 'We noticed a new login to your X account. If this was you, you can ignore this message. If not, please secure your account.', time: '9:50 PM', domain: 'x.com', read: false, starred: true, favorited: true, folder: 'inbox', labels: ['Important', 'Security'], muted: false },
  { id: 2, from: 'Google', subject: 'Security alert - New sign-in to your account', body: 'A new sign-in was detected on your Google account. Check your security settings for more details.', time: '5:27 PM', domain: 'google.com', read: true, starred: false, favorited: false, folder: 'inbox', labels: ['Security'], muted: false },
  { id: 3, from: 'Windsurf Team', subject: 'Claude Opus 4.5 Pricing Update', body: 'Hello! Our Claude Opus 4.5 promotional period will end on December 31st. Upgrade now to keep your benefits.', time: '3:37 PM', domain: 'windsurf.dev', read: false, starred: false, favorited: false, folder: 'inbox', labels: ['Promotions'], muted: false },
  { id: 4, from: 'K PLUS', subject: 'Result of Bill Payment (Success)', body: 'Your bill payment of 1,200 THB to TRUE INTERNET was successful.', time: '3:10 PM', domain: 'kasikornbank.com', read: true, starred: true, favorited: false, folder: 'purchases', labels: ['Finance', 'Receipt'], muted: false },
  { id: 5, from: 'Kiana', subject: 'Vy for Windows is ready for you!', body: 'Image Vy is now available on Windows! Hi, This is Kiana, CEO and cofounder of Vy. We are excited to announce that Vy is now available on Windows.', time: '10:00 AM', domain: 'vy.com', read: false, starred: false, favorited: true, folder: 'inbox', labels: ['Updates'], muted: false },
  { id: 6, from: 'npm', subject: 'Successfully published @newkubise/cli@0.0.0', body: 'Hi newkubise! A new version of the package @newkubise/cli@0.0.0 has been published. You can view it here: https://www.npmjs.com/package/@newkubise/cli', time: '4:04 AM', domain: 'npmjs.com', read: true, starred: false, favorited: false, folder: 'sent', labels: ['Dev'], muted: false },
  { id: 7, from: 'Kyle Galbraith', subject: 'Upcoming GitHub pricing change', body: 'Hi there, We wanted to reach out to let you know about an upcoming change to GitHub Actions. This will not affect your current plan.', time: '12:55 AM', domain: 'github.com', read: false, starred: false, favorited: false, folder: 'drafts', labels: ['Dev', 'GitHub'], muted: false },
  { id: 8, from: 'GitHub', subject: 'GitHub is updating the Actions pricing structure', body: 'GitHub You are receiving this email because you have used GitHub Actions. We are updating our pricing structure to better reflect the value of our services.', time: '12:51 AM', domain: 'github.com', read: true, starred: true, favorited: true, folder: 'inbox', labels: ['Dev', 'GitHub'], muted: false },
  { id: 9, from: 'Vercel', subject: 'Deployment Successful: email-clone', body: 'Your deployment for the project email-clone is now live. You can view it at https://email-clone.vercel.app', time: 'Yesterday', domain: 'vercel.com', read: true, starred: false, favorited: false, folder: 'inbox', labels: ['Dev', 'Vercel'], muted: false },
  { id: 10, from: 'Linear', subject: 'New issue assigned to you: [BUG] - Sidebar toggle not working', body: 'A new issue has been assigned to you in the project Email App. Please review and provide an update.', time: 'Yesterday', domain: 'linear.app', read: false, starred: false, favorited: false, folder: 'inbox', labels: ['Work', 'Bugs'], muted: false },
  { id: 11, from: 'Figma', subject: 'John Doe invited you to a new file', body: 'John Doe has invited you to view the file \'Email App Mockup\'. Click here to view the file.', time: '2 days ago', domain: 'figma.com', read: true, starred: false, favorited: false, folder: 'inbox', labels: ['Work', 'Design'], muted: false },
  { id: 12, from: 'Me', to: 'test@example.com', subject: 'Test Email', body: 'This is a test email sent from the app.', time: '3 days ago', domain: 'email.com', read: true, starred: false, favorited: false, folder: 'sent', labels: [], muted: false },
  { id: 13, from: 'Me', to: 'boss@example.com', subject: 'Project Update', body: 'Here is the project update you requested.', time: '4 days ago', domain: 'email.com', read: true, starred: false, favorited: false, folder: 'drafts', labels: ['Work'], muted: false },
  { id: 14, from: 'Shopee', subject: 'Order Confirmation #SHP12345', body: 'Thank you for your order! Your purchase of 1 item(s) for 599 THB is confirmed.', time: '5 days ago', domain: 'shopee.co.th', read: true, starred: false, favorited: false, folder: 'purchases', labels: ['Receipt'], muted: false },
  { id: 15, from: 'Lazada', subject: 'Your order #LAZ67890 has been shipped!', body: 'Great news! Your order containing a new keyboard is on its way.', time: '6 days ago', domain: 'lazada.co.th', read: true, starred: false, favorited: false, folder: 'purchases', labels: ['Updates'], muted: false },
  { id: 16, from: 'Netflix', subject: 'Your subscription has been renewed', body: 'Your Netflix subscription has been renewed for 169 THB.', time: '7 days ago', domain: 'netflix.com', read: true, starred: false, favorited: false, folder: 'purchases', labels: ['Finance', 'Receipt'], muted: false },
];

