import { writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { ContentConfig, ContentCollection } from "../../shared/types/collection";

export async function generateTypes(config: ContentConfig, buildDir: string): Promise<void> {
  const typesDir = join(buildDir, "types");
  await mkdir(typesDir, { recursive: true });

  let typesContent = `// Auto-generated by wcontent
// Do not edit manually

import type { ParsedContent, QueryBuilder } from "@wrikka/wcontent/runtime";

`;

  // Generate types for each collection
  for (const [name, collection] of Object.entries(config.collections)) {
    const typeName = toPascalCase(name) + "Collection";
    
    // Extract schema type (simplified - in production would use zod-to-ts)
    typesContent += `export interface ${typeName} extends ParsedContent {
  // Collection: ${name}
  // Source: ${Array.isArray(collection.source) ? collection.source.join(", ") : collection.source}
`;

    // Add inferred fields from schema
    typesContent += `  // Schema fields inferred from content.config.ts\n`;
    typesContent += `}\n\n`;

    // Generate query builder type
    typesContent += `export interface ${typeName}QueryBuilder extends QueryBuilder<${typeName}> {}\n\n`;
  }

  // Generate collections map
  typesContent += `export interface Collections {\n`;
  for (const name of Object.keys(config.collections)) {
    const typeName = toPascalCase(name) + "Collection";
    typesContent += `  "${name}": ${typeName};\n`;
  }
  typesContent += `}\n\n`;

  // Generate queryContent function overloads
  typesContent += `declare module "@wrikka/wcontent/runtime" {\n`;
  typesContent += `  export function queryContent<T extends keyof Collections>(\n`;
  typesContent += `    collection: T\n`;
  typesContent += `  ): QueryBuilder<Collections[T]>\n`;
  typesContent += `}\n`;

  await writeFile(join(typesDir, "content.d.ts"), typesContent);
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_]/g, " ")
    .replace(/(?:^\w|[A-Z]|\b\w)/g, (word) => word.toUpperCase())
    .replace(/\s+/g, "");
}
